version: '3.9'

services:
  db:
    image: kauahensilva/orientdb:2.2.37
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: 'root'
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - wifi_network

networks:
  wifi_network:
    external: true
